# ===============================
# CONNESSIONE AL DATABASE MYSQL
# ===============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# CONFIGURAZIONE JPA E HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
server.port=${PORT:8084}
application.security.jwt.secret-key=${JWT_SECRET_KEY}
application.security.jwt.expiration=${JWT_EXPIRATION}

# ===============================
# CONNESSIONE A REDIS
# ===============================
spring.data.redis.host=${REDIS_URL}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.port=10155
spring.data.redis.username=${REDIS_USERNAME}
spring.data.redis.ssl.enabled=true
spring.data.redis.repositories.enabled=false

# ===============================
# EMAIL
# ===============================
spring.mail.host=smtp.resend.com
spring.mail.port=465
spring.mail.username=resend
spring.mail.password=${RESEND_API_KEY}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
mail.from=${MAIL_FROM}

# ===============================
# CONFIGURAZIONE KAFKA (AIVEN)
# ===============================
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}

# Sicurezza obbligatoria per Aiven Cloud
spring.kafka.properties.security.protocol=SASL_SSL
spring.kafka.properties.sasl.mechanism=SCRAM-SHA-256
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required \
    username="${KAFKA_USERNAME}" \
    password="${KAFKA_PASSWORD}";

# --- CERTIFICATO SSL ---
spring.kafka.ssl.trust-store-location=${KAFKA_TRUSTSTORE_LOCATION:classpath:client.truststore.jks}
spring.kafka.ssl.trust-store-password=changeit
spring.kafka.ssl.trust-store-type=JKS
# ------------------------------------------

# Serializzazione per inviare e ricevere oggetti Java come JSON
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Configurazione del Consumer
spring.kafka.consumer.group-id=yumaste-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# ===============================
# CONFIGURAZIONE PROMETHEUS
# ===============================

management.endpoints.web.exposure.include=health,prometheus,metrics
management.metrics.tags.application=yumaste-api


# ===============================
# INTELLIGENZA ARTIFICIALE - GEMINI SDK
# ===============================
gemini.api.key=${GEMINI_API_KEY}
